title: Titanc3
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
